# Pretty similar for MySQL/MariaDB
# In case of this file, PostgreSQL host is postgres:5432
---
version: "3"

services:
  bmonitord:
    container_name: bmonitord
    image: bartosz11/bmonitord:v2
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - bmonitord:/home/root
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    #Just in case, you might not need this
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      #Set these credentials in application.yml
      #Note: this user will have root privileges! This might be dangerous, so consider removing this variable and creating a user through psql instead
      POSTGRES_USER: bmonitord
      #This is required even if you removed the variable above
      POSTGRES_PASSWORD: CHANGE_ME
      #Database name - this technically is not required, postgres would just use the username
      POSTGRES_DB: bmonitord

# If you leave those volumes as external, you'll have to create them manually with "docker volume create"
volumes:
  bmonitord:
    external: true
  postgres:
    external: true
