---
version: "3"

services:
  bmonitord:
    container_name: bmonitord
    image: bartosz11/bmonitord:v2
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - bmonitord:/home/root
    environment:
      TZ: "Europe/Warsaw"

volumes:
  bmonitord:
    external: true
