#NS in this file's name stands for "no setup" - you only need docker installed to build this dockerfile - the other one is meant for CI's and stuff

FROM node:18-bullseye-slim AS build_node
COPY frontend /home/root
WORKDIR /home/root
RUN npm i && npm run build
RUN gzip --keep --best -r dist/

FROM gradle:8.1-jdk17-alpine AS build_java
WORKDIR /home/root
COPY src src/
COPY build.gradle .
COPY settings.gradle .
COPY --from=build_node /home/root/dist src/main/resources/static
RUN gradle bootJar --no-daemon

FROM eclipse-temurin:17-jre-jammy AS run
COPY --from=build_java /home/root/build/libs/bmonitord.jar /bin/bmonitord.jar
#https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#sort-multi-line-arguments
RUN apt update && apt install iputils-ping curl -y --no-install-recommends && rm -rf /var/lib/apt/lists/*
#App has to run as root for ping check provider to work properly
WORKDIR /home/root
VOLUME /home/root
#Consider switching your mail server if it causes a healthcheck with 15s timeout to fail /j
#bmonitord takes a while to start, so 120s start period
HEALTHCHECK --interval=45s --timeout=15s --start-period=120s \
  CMD curl --fail http://127.0.0.1:8080/app/health || exit 1
#default port
EXPOSE 8080
ENTRYPOINT exec java -jar /bin/bmonitord.jar
