create table agents (id uuid not null, agent_version varchar(255), cpu_cores integer not null, cpu_model varchar(255), installed boolean not null, ip_address varchar(255), last_data_received bigint not null, os varchar(255), ram_total bigint not null, swap_total bigint not null, uptime integer not null, monitor_id bigint, primary key (id));
create table heartbeats (id bigserial not null, cpu_frequency integer not null, cpu_usage float4 not null, disk_data varchar(255), disks_usage float4 not null, iowait float4 not null, ram_usage float4 not null, response_time bigint not null, rx bigint not null, status smallint, swap_usage float4 not null, timestamp bigint not null, tx bigint not null, monitor_id bigint, primary key (id));
create table incidents (id bigserial not null, duration bigint not null, end_timestamp bigint not null, ongoing boolean not null, start_timestamp bigint not null, monitor_id bigint, primary key (id));
create table monitors (id bigserial not null, allowed_http_codes varchar(255), checks_down integer not null, checks_up integer not null, created_on bigint not null, host varchar(255), last_check bigint not null, last_status smallint, last_successful_check bigint not null, name varchar(255), paused boolean not null, published boolean not null, retries integer not null, timeout integer not null, type smallint, verify_certificate boolean not null, agent_id uuid, user_id bigint, primary key (id));
create table monitors_heartbeats (monitor_id bigint not null, heartbeats_id bigint not null);
create table monitors_incidents (monitor_id bigint not null, incidents_id bigint not null);
create table monitors_notifications (monitor_id bigint not null, notifications_id bigint not null);
create table monitors_statuspages (monitor_id bigint not null, statuspages_id bigint not null);
create table notifications (id bigserial not null, credentials varchar(255), name varchar(255), type smallint, user_id bigint, primary key (id));
create table notifications_monitors (notification_id bigint not null, monitors_id bigint not null);
create table statuspage_announcements (id bigserial not null, content varchar(255), title varchar(255), type smallint, statuspage_id bigint, primary key (id));
create table statuspages (id bigserial not null, name varchar(255), announcement_id bigint, user_id bigint, primary key (id));
create table statuspages_monitors (statuspage_id bigint not null, monitors_id bigint not null);
create table users (id bigserial not null, enabled boolean not null, last_updated bigint not null, password varchar(255), username varchar(255), primary key (id));
alter table monitors_heartbeats add constraint monitors_heartbeats_hb_id_unique unique (heartbeats_id);
alter table monitors_incidents add constraint monitors_incidents_ic_id_unique unique (incidents_id);
alter table agents add constraint agents_monitor_id_fk foreign key (monitor_id) references monitors;
alter table heartbeats add constraint heartbeats_monitor_id_fk foreign key (monitor_id) references monitors;
alter table incidents add constraint incidents_monitor_id_fk foreign key (monitor_id) references monitors;
alter table monitors add constraint monitors_agent_id_fk foreign key (agent_id) references agents;
alter table monitors add constraint monitors_user_id_fk foreign key (user_id) references users;
alter table monitors_heartbeats add constraint monitors_heartbeats_hb_id_ref foreign key (heartbeats_id) references heartbeats;
alter table monitors_heartbeats add constraint monitors_heartbeats_monitor_id_ref foreign key (monitor_id) references monitors;
alter table monitors_incidents add constraint monitors_incidents_ic_id_ref foreign key (incidents_id) references incidents;
alter table monitors_incidents add constraint monitors_incidents_monitor_id_ref foreign key (monitor_id) references monitors;
alter table monitors_notifications add constraint monitors_notifications_nt_id_ref foreign key (notifications_id) references notifications;
alter table monitors_notifications add constraint monitors_notifications_monitor_id_ref foreign key (monitor_id) references monitors;
alter table monitors_statuspages add constraint monitors_statuspages_st_id_ref foreign key (statuspages_id) references statuspages;
alter table monitors_statuspages add constraint monitors_statuspages_monitor_id_ref foreign key (monitor_id) references monitors;
alter table notifications add constraint notifications_user_id_ref foreign key (user_id) references users;
alter table notifications_monitors add constraint notifications_monitors_monitor_id_ref foreign key (monitors_id) references monitors;
alter table notifications_monitors add constraint notifications_monitors_nt_id_ref foreign key (notification_id) references notifications;
alter table statuspage_announcements add constraint statuspage_announcements_st_id_ref foreign key (statuspage_id) references statuspages;
alter table statuspages add constraint statuspages_announcement_id_ref foreign key (announcement_id) references statuspage_announcements;
alter table statuspages add constraint statuspages_user_id_ref foreign key (user_id) references users;
alter table statuspages_monitors add constraint statuspages_monitors_monitor_id_ref foreign key (monitors_id) references monitors;
alter table statuspages_monitors add constraint statuspages_monitors_st_id_ref foreign key (statuspage_id) references statuspages;