db:
  host: "host"
  port: "5432"
  username: "postgres"
  password: ""
  database: "checkmate"
  sslmode: "disable"
  timezone: "Europe/Warsaw"

email:
  host: "smtp.example.com"
  port: 587
  username: "replace_me"
  password: "replace"
  ssl: false # most providers use STARTTLS and don't want SSL connections on port 587, port 465 usually means SSL = true
  from: "replace_me" # usually the same as username, basically the email address messages will be sent from

orchestrator:
  # How long the should the orchestrator wait for checkers to send back the check result on top of each target's timeout? in ms, 1 second = 1000 ms
  # Going over 1000 is not recommended, 500 should be enough in most cases, although you can increase it if you see lots of "target not queued" errors in logs
  max-network-overhead: 500
  # How long should the orchestrator wait after taking over leadership before starting to check on push targets (for example agent targets)?
  # In minutes. This is a behavior reimplemented from bmonitord v2, where checks on agent monitors weren't being run for the first 5 minutes of instance's uptime
  # Note that it doesn't stop processing THRESHOLD alarms when agent sends data that can trigger one assigned to it
  # Setting this to 0 will disable this behavior entirely
  grace-period: 1
  name: "replace_me" # This is ignored by the AIO binary/image

# Keep these settings in sync across all API instances you're hosting if you're hosting multiple!
api:
  jwt-secret: replace_me
  jwt-validity: 360 # in minutes, 6hrs by default
  host-docs: true # Should this API instance also host swagger API docs? if true, they'll be available at /swagger/index.html
  secure-cookies: false # Set to true if your instance is accessible through https. Cookies will have the "Secure" flag
  host-frontend: true # Should this API instance also host the web dashboard? note that it's  bundled in the binary and disabling this won't make the binary/docker image lighter
  # How many Argon2id hashing operations are allowed in parallel? Each can consume around 64MB of RAM.
  # This may affect performance of login/register/change password operations if you have many users performing these simultaneously. Lowest allowed value is 1.
  hashing-pool-size: 2

checker:
  key: replace_me # This is ignored by the AIO binary/image
  # URL's of orchestrators the checker should connect to
  # If you're using the AIO image/binary, don't add the built-in orchestrator's host here, only other orchestrators in the cluster (if you have any)
  orchestrators:
#    - ws://example.com/orchestrator/ws
#    - wss://example2.com/orchestrator/ws


# https://github.com/rs/zerolog?tab=readme-ov-file#leveled-logging
# Keep it at 1 in most cases
logging-level: 1
pretty-logging: true
# Pretty much affects only CORS settings, setting this to false will allow localhost:5173 access the entire API, useful for frontend development
# If true, Gin's mode will be set to Release, otherwise it will stay at Debug
production: true
# You can change the IP address the API/orchestrator listens on here. If you're running checkmate inside Docker, please change the host-side port instead
# :8080 means "bind to port 8080 on all interfaces", more info here: https://gin-gonic.com/en/docs/deployment/#configuration-options
# In AIO binary/image, this address will also be used by the built-in checker to access the built-in orchestrator
bind: ":8080"