create table agents (id blob not null, agent_version varchar(255), cpu_cores integer not null, cpu_model varchar(255), installed boolean not null, ip_address varchar(255), last_data_received bigint not null, os varchar(255), ram_total bigint not null, swap_total bigint not null, uptime integer not null, monitor_id bigint, primary key (id));
create table heartbeats (id integer, cpu_frequency integer not null, cpu_usage float not null, disk_data varchar(255), disks_usage float not null, iowait float not null, ram_usage float not null, response_time bigint not null, rx bigint not null, status smallint, swap_usage float not null, timestamp bigint not null, tx bigint not null, monitor_id bigint, primary key (id));
create table incidents (id integer, duration bigint not null, end_timestamp bigint not null, ongoing boolean not null, start_timestamp bigint not null, monitor_id bigint, primary key (id));
create table monitors (id integer, allowed_http_codes varchar(255), checks_down integer not null, checks_up integer not null, created_on bigint not null, host varchar(255), last_check bigint not null, last_status smallint, last_successful_check bigint not null, name varchar(255), paused boolean not null, published boolean not null, retries integer not null, timeout integer not null, type smallint, verify_certificate boolean not null, agent_id blob, user_id bigint, primary key (id));
create table monitors_heartbeats (monitor_id bigint not null, heartbeats_id bigint not null);
create table monitors_incidents (monitor_id bigint not null, incidents_id bigint not null);
create table monitors_notifications (monitor_id bigint not null, notifications_id bigint not null);
create table monitors_statuspages (monitor_id bigint not null, statuspages_id bigint not null);
create table notifications (id integer, credentials varchar(255), name varchar(255), type smallint, user_id bigint, primary key (id));
create table notifications_monitors (notification_id bigint not null, monitors_id bigint not null);
create table statuspage_announcements (id integer, content varchar(255), title varchar(255), type smallint, statuspage_id bigint, primary key (id));
create table statuspages (id integer, name varchar(255), announcement_id bigint, user_id bigint, primary key (id));
create table statuspages_monitors (statuspage_id bigint not null, monitors_id bigint not null);
create table users (id integer, enabled boolean not null, last_updated bigint not null, password varchar(255), username varchar(255), primary key (id));