orchestrator:
  db:
    host: "host"
    port: "5432"
    username: "postgres"
    password: ""
    database: "bmonitord"
    sslmode: "disable"
    timezone: "Europe/Warsaw"
  max-network-overhead: 500
  name: "replace_me"

# https://github.com/rs/zerolog?tab=readme-ov-file#leveled-logging
# Keep it at 1 in most cases
logging-level: 1
pretty-logging: true
