create table agents (id binary(16) not null, agent_version varchar(255), cpu_cores integer not null, cpu_model varchar(255), installed boolean not null, ip_address varchar(255), last_data_received bigint not null, os varchar(255), ram_total bigint not null, swap_total bigint not null, uptime integer not null, monitor_id bigint, primary key (id)) engine=InnoDB;
create table heartbeats (id bigint not null auto_increment, cpu_frequency integer not null, cpu_usage float4 not null, disk_data varchar(255), disks_usage float4 not null, iowait float4 not null, ram_usage float4 not null, response_time bigint not null, rx bigint not null, status smallint, swap_usage float4 not null, timestamp bigint not null, tx bigint not null, monitor_id bigint, primary key (id)) engine=InnoDB;
create table incidents (id bigint not null auto_increment, duration bigint not null, end_timestamp bigint not null, ongoing boolean not null, start_timestamp bigint not null, monitor_id bigint, primary key (id)) engine=InnoDB;
create table monitors (id bigint not null auto_increment, allowed_http_codes varchar(255), checks_down integer not null, checks_up integer not null, created_on bigint not null, host varchar(255), last_check bigint not null, last_status smallint, last_successful_check bigint not null, name varchar(255), paused boolean not null, published boolean not null, retries integer not null, timeout integer not null, type smallint, verify_certificate boolean not null, agent_id binary(16), user_id bigint, primary key (id)) engine=InnoDB;
create table monitors_heartbeats (monitor_id bigint not null, heartbeats_id bigint not null) engine=InnoDB;
create table monitors_incidents (monitor_id bigint not null, incidents_id bigint not null) engine=InnoDB;
create table monitors_notifications (monitor_id bigint not null, notifications_id bigint not null) engine=InnoDB;
create table monitors_statuspages (monitor_id bigint not null, statuspages_id bigint not null) engine=InnoDB;
create table notifications (id bigint not null auto_increment, credentials varchar(255), name varchar(255), type smallint, user_id bigint, primary key (id)) engine=InnoDB;
create table notifications_monitors (notification_id bigint not null, monitors_id bigint not null) engine=InnoDB;
create table statuspage_announcements (id bigint not null auto_increment, content varchar(255), title varchar(255), type smallint, statuspage_id bigint, primary key (id)) engine=InnoDB;
create table statuspages (id bigint not null auto_increment, name varchar(255), announcement_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table statuspages_monitors (statuspage_id bigint not null, monitors_id bigint not null) engine=InnoDB;
create table users (id bigint not null auto_increment, enabled boolean not null, last_updated bigint not null, password varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
alter table monitors_heartbeats drop constraint if exists monitors_heartbeats_hb_id_unique;
alter table monitors_heartbeats add constraint monitors_heartbeats_hb_id_unique unique (heartbeats_id);
alter table monitors_incidents drop constraint if exists monitors_incidents_ic_id_unique;
alter table monitors_incidents add constraint monitors_incidents_ic_id_unique unique (incidents_id);
alter table agents drop constraint if exists agents_monitor_id_fk;
alter table agents add constraint agents_monitor_id_fk foreign key (monitor_id) references monitors (id);
alter table heartbeats drop constraint if exists heartbeats_monitor_id_fk;
alter table heartbeats add constraint heartbeats_monitor_id_fk foreign key (monitor_id) references monitors (id);
alter table incidents drop constraint if exists incidents_monitor_id_fk;
alter table incidents add constraint incidents_monitor_id_fk foreign key (monitor_id) references monitors (id);
alter table monitors drop constraint if exists monitors_agent_id_fk;
alter table monitors add constraint monitors_agent_id_fk foreign key (agent_id) references agents (id);
alter table monitors drop constraint if exists monitors_user_id_fk;
alter table monitors add constraint monitors_user_id_fk foreign key (user_id) references users (id);
alter table monitors_heartbeats drop constraint if exists monitors_heartbeats_hb_id_ref;
alter table monitors_heartbeats add constraint monitors_heartbeats_hb_id_ref foreign key (heartbeats_id) references heartbeats (id);
alter table monitors_heartbeats drop constraint if exists monitors_heartbeats_monitor_id_ref;
alter table monitors_heartbeats add constraint monitors_heartbeats_monitor_id_ref foreign key (monitor_id) references monitors (id);
alter table monitors_incidents drop constraint if exists monitors_incidents_ic_id_ref;
alter table monitors_incidents add constraint monitors_incidents_ic_id_ref foreign key (incidents_id) references incidents (id);
alter table monitors_incidents drop constraint if exists monitors_incidents_monitor_id_ref;
alter table monitors_incidents add constraint monitors_incidents_monitor_id_ref foreign key (monitor_id) references monitors (id);
alter table monitors_notifications drop constraint if exists monitors_notifications_nt_id_ref;
alter table monitors_notifications add constraint monitors_notifications_nt_id_ref foreign key (notifications_id) references notifications (id);
alter table monitors_notifications drop constraint if exists monitors_notifications_monitor_id_ref;
alter table monitors_notifications add constraint monitors_notifications_monitor_id_ref foreign key (monitor_id) references monitors (id);
alter table monitors_statuspages drop constraint if exists monitors_statuspages_st_id_ref;
alter table monitors_statuspages add constraint monitors_statuspages_st_id_ref foreign key (statuspages_id) references statuspages (id);
alter table monitors_statuspages drop constraint if exists monitors_statuspages_monitor_id_ref;
alter table monitors_statuspages add constraint monitors_statuspages_monitor_id_ref foreign key (monitor_id) references monitors (id);
alter table notifications drop constraint if exists notifications_user_id_ref;
alter table notifications add constraint notifications_user_id_ref foreign key (user_id) references users (id);
alter table notifications_monitors drop constraint if exists notifications_monitors_monitor_id_ref;
alter table notifications_monitors add constraint notifications_monitors_monitor_id_ref foreign key (monitors_id) references monitors (id);
alter table notifications_monitors drop constraint if exists notifications_monitors_nt_id_ref;
alter table notifications_monitors add constraint notifications_monitors_nt_id_ref foreign key (notification_id) references notifications (id);
alter table statuspage_announcements drop constraint if exists statuspage_announcements_st_id_ref;
alter table statuspage_announcements add constraint statuspage_announcements_st_id_ref foreign key (statuspage_id) references statuspages (id);
alter table statuspages drop constraint if exists statuspages_announcement_id_ref;
alter table statuspages add constraint statuspages_announcement_id_ref foreign key (announcement_id) references statuspage_announcements (id);
alter table statuspages drop constraint if exists statuspages_user_id_ref;
alter table statuspages add constraint statuspages_user_id_ref foreign key (user_id) references users (id);
alter table statuspages_monitors drop constraint if exists statuspages_monitors_monitor_id_ref;
alter table statuspages_monitors add constraint statuspages_monitors_monitor_id_ref foreign key (monitors_id) references monitors (id);
alter table statuspages_monitors drop constraint if exists statuspages_monitors_st_id_ref;
alter table statuspages_monitors add constraint statuspages_monitors_st_id_ref foreign key (statuspage_id) references statuspages (id);