name: Build JAR and Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        id: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        id: setup_env
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set gradlew permissions
        id: set_gradle_perms
        run: chmod u+x gradlew
      - name: Build with Gradle
        id: gradle_build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar --no-daemon
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/monitoring:latest