name: Build JAR and Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        id: checkout
        uses: actions/checkout@v2
      - name: Check for CI skip
        id: ci_skip_check
        uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - name: Set up JDK 11
        id: setup_env
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set gradlew permissions
        id: set_gradle_perms
        run: chmod u+x gradlew
      - name: Build with Gradle
        id: gradle_build
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: bootJar --no-daemon
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/monitoring:latest